apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
       name: webappreplica9
       labels:
            app: webappreplica9
spec: 
    replicas: 3
    template:
      metadata:  
         labels: 
            app: webappreplica9
      spec:
        containers:
            - name: mypod-cont1
              image: nginx:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: http
                  containerPort: 80
                  protocol: TCP
    selector: 
          matchExpressions: 
            #- {key: app, operator: NotIn, values: [webappreplica, webappreplica2]}
            -  { key: app, operator: Exists}