apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webappreplica
  labels:
    app: webapp-new
spec:
  replicas: 5
  
  template:
    metadata:
      labels:
        app: webapp-new
    spec:
      containers:
      - name: webapp-container
        image: nginx:latest 
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: webapp-new